/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kasiracc;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rizki Trisna
 */
public class FrameTableEnteredCashierPopUp extends javax.swing.JFrame {

    /**
     * Creates new form FrameTableEnteredCashierPopUp
     */
    static Connection conn;
    static Statement stmt;
    static ResultSet rs;

    public FrameTableEnteredCashierPopUp() {
        setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
        try {
            getKoneksi();
        } catch (SQLException ex) {
            Logger.getLogger(FrameTableEnteredCashierPopUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        setDetail();
    }

    private void getKoneksi() throws SQLException {
        koneksi kon = new koneksi();
        conn = kon.getConnection();
    }

    private Object[] cariDataBarang(int id_barang) {
        try {
            Object[] ob = new Object[5];

            stmt = conn.createStatement();

            String query = "Select * from barang where id_barang=" + id_barang;

            rs = stmt.executeQuery(query);

            while (rs.next()) {
                ob[0] = rs.getInt("id_barang");
                ob[1] = rs.getInt("id_jenis_barang");
                String nama_barang = rs.getString("nama_barang");
                if (nama_barang.length() > 14) { 
                    ob[2] = nama_barang.substring(0, 14) + "..";
                } else {
                    ob[2] = nama_barang ; 
                }
                ob[3] = rs.getInt("harga_jual");
                ob[4] = rs.getInt("stok_barang");
            }
            return ob;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    private void setDetail() {
        Object[] data_barang = cariDataBarang(Transaksi.getId_barang());
        int subtotal = Integer.parseInt(data_barang[3].toString()) * Transaksi.getQty();

        lbl_id.setText(Transaksi.getId_barang() + "");
        lbl_nama_barang.setText(data_barang[2].toString());
        tf_qty.setText(Transaksi.getQty() + "");
        lbl_harga.setText(data_barang[3].toString());
        lbl_subtotal.setText(subtotal + "");

    }

    private static String convertToCurrency(double number) {
        DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
        DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

        formatRp.setCurrencySymbol("Rp. ");
        formatRp.setMonetaryDecimalSeparator(',');
        formatRp.setGroupingSeparator('.');
        kursIndonesia.setDecimalFormatSymbols(formatRp);
        String result = kursIndonesia.format(number);

        return result;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_nama_barang = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbl_subtotal = new javax.swing.JLabel();
        lbl_id = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lbl_harga = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tf_qty = new javax.swing.JTextField();
        lbl_batalkan = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        jLabel2.setText("Nama Barang");

        jLabel3.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        jLabel3.setText("Banyaknya");

        jLabel4.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        jLabel4.setText("Harga");

        jLabel5.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        jLabel5.setText("Subtotal");

        jLabel6.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        jLabel6.setText(":");

        lbl_nama_barang.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        lbl_nama_barang.setText("XXXXXXXX");

        jLabel9.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        jLabel9.setText("Rp.");

        lbl_subtotal.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        lbl_subtotal.setText("0000000");

        lbl_id.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        lbl_id.setText("XXXXXXXX");

        jLabel12.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        jLabel12.setText(":");

        jLabel13.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        jLabel13.setText(":");

        jLabel14.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        jLabel14.setText(":");

        jLabel15.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        jLabel15.setText(":");

        lbl_harga.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        lbl_harga.setText("0");

        jLabel17.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        jLabel17.setText("Rp.");

        tf_qty.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        tf_qty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_qtyActionPerformed(evt);
            }
        });
        tf_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_qtyKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_qtyKeyTyped(evt);
            }
        });

        lbl_batalkan.setFont(new java.awt.Font("Assistant", 0, 26)); // NOI18N
        lbl_batalkan.setForeground(new java.awt.Color(168, 168, 168));
        lbl_batalkan.setText("Batalkan");
        lbl_batalkan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_batalkanMouseClicked(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(251, 136, 134));
        jButton1.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Keluarkan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(26, 115, 232));
        jButton2.setFont(new java.awt.Font("Assistant SemiBold", 0, 26)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ubah Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(lbl_batalkan))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel12))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13))
                                .addComponent(jLabel4)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(133, 133, 133)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_nama_barang)
                            .addComponent(lbl_id)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_harga)
                                    .addComponent(lbl_subtotal)))
                            .addComponent(tf_qty))))
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_id)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_nama_barang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_qty, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(lbl_harga))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl_subtotal)
                                    .addComponent(jLabel17)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14)))
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)))
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_batalkan)
                .addGap(39, 39, 39))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_qtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_qtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_qtyActionPerformed

    private void lbl_batalkanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_batalkanMouseClicked

        this.dispose();
    }//GEN-LAST:event_lbl_batalkanMouseClicked

    private void tf_qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_qtyKeyTyped
        filterAngka(evt);
    }//GEN-LAST:event_tf_qtyKeyTyped

    private void tf_qtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_qtyKeyReleased
        if (!tf_qty.getText().equals("")) {
            int harga_barang = Integer.parseInt(cariDataBarang(Transaksi.getId_barang())[3].toString());
            int qty = Integer.parseInt(tf_qty.getText().toString());
            int subtotal = harga_barang * qty;

            lbl_subtotal.setText(subtotal + "");

        } else {
            lbl_subtotal.setText("0");
        }
    }//GEN-LAST:event_tf_qtyKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // hapus data dari keranjang
        try {

            int qty_lama = Transaksi.getQty();
            int stok_lama = Integer.parseInt(cariDataBarang(Transaksi.getId_barang())[4].toString());
            int stok_baru = qty_lama + stok_lama;
            int hasil = JOptionPane.showConfirmDialog(null, "Keluarkan barang ini dari keranjang?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (hasil == JOptionPane.YES_OPTION) {
                // Hapus data barang by id di tabel temp_transaksi
                String query = "Delete from temp_transaksi where id_barang=" + Transaksi.getId_barang();
                PreparedStatement pst = conn.prepareStatement(query);
                pst.execute();

                // Update stok lama jadi stok baru dengan menambahkan qty yang dimasukkan ke temp_transaksi by id barang
                query = "update barang set stok_barang=" + stok_baru + " where id_barang=" + Transaksi.getId_barang();
                pst = conn.prepareStatement(query);
                pst.execute();

                FrameCashier.refreshKeranjang();
                FrameCashier.refreshTabelBarang();
                this.dispose();
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        // tambahkan qty dari keranjang ke stok di inventory

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Get qty
        Object[] data_barang = cariDataBarang(Transaksi.getId_barang());
        int qty_lama = Transaksi.getQty();
        int qty_baru = Integer.parseInt(tf_qty.getText());
        int stok_barang = Integer.parseInt(data_barang[4].toString());
        int stok_temp = stok_barang + qty_lama;
        //cek apakah qty melebihi stok
        if (!tf_qty.getText().equals("")) {

            if (qty_baru <= stok_temp) {

                if (qty_baru != 0) {
                    try {
                        int stok_baru = stok_temp - qty_baru;
                        // update qty di db temp
                        String query = "update temp_transaksi set qty=" + qty_baru + " where id_barang=" + Transaksi.getId_barang();
                        PreparedStatement pst = conn.prepareStatement(query);
                        pst.execute();
                        // update stok di db barang
                        query = "update barang set stok_barang=" + stok_baru + " where id_barang=" + Transaksi.getId_barang();
                        pst = conn.prepareStatement(query);
                        pst.execute();
                        // refresh tabel
                        FrameCashier.refreshTabelBarang();
                        FrameCashier.refreshKeranjang();
                        // refresh detail pembayaran
                        FrameCashier.refreshDetailPembayaran();
                        this.dispose();
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat update data barang\n Error: " + e);
                    }

                } else {
                    //hapus barang dari keranjang
                    try {

                        int stok_lama = Integer.parseInt(cariDataBarang(Transaksi.getId_barang())[4].toString());
                        int stok_baru = qty_lama + stok_lama;
                        int hasil = JOptionPane.showConfirmDialog(null, "Keluarkan barang ini dari keranjang?", "", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                        if (hasil == JOptionPane.YES_OPTION) {
                            // Hapus data barang by id di tabel temp_transaksi
                            String query = "Delete from temp_transaksi where id_barang=" + Transaksi.getId_barang();
                            PreparedStatement pst = conn.prepareStatement(query);
                            pst.execute();

                            // Update stok lama jadi stok baru dengan menambahkan qty yang dimasukkan ke temp_transaksi by id barang
                            query = "update barang set stok_barang=" + stok_baru + " where id_barang=" + Transaksi.getId_barang();
                            pst = conn.prepareStatement(query);
                            pst.execute();

                            FrameCashier.refreshKeranjang();
                            FrameCashier.refreshTabelBarang();
                            this.dispose();
                        }

                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }

            } else {
                JOptionPane.showMessageDialog(null, "Jumlah stok barang tidak mencukupi\n Sisa stok barang sekarang: " + stok_temp);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Kolom jumlah barang/qty tidak boleh kosong");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private boolean filterAngka(KeyEvent evt) {
        if (Character.isAlphabetic(evt.getKeyChar())) {
            //JIKA KARAKTER YANG DIINPUTKAN ADALAH ALPHABET, MAKA TIDAK AKAN DIPROSES OLEH KEYLISTENER KARENA DICEGAH METHOD CONSUME
            //DAN AKAN MENAMPILKAN PESAN JOPTIONPANE "FIELD INI HANYA MENERIMA INPUT ANGKA
            evt.consume();
            JOptionPane.showMessageDialog(null, "Field ini hanya menerima input Angka");
            return false;
        } else {
            return true;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTableEnteredCashierPopUp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTableEnteredCashierPopUp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTableEnteredCashierPopUp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTableEnteredCashierPopUp.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTableEnteredCashierPopUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_batalkan;
    private javax.swing.JLabel lbl_harga;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_nama_barang;
    private javax.swing.JLabel lbl_subtotal;
    private javax.swing.JTextField tf_qty;
    // End of variables declaration//GEN-END:variables
}
